### ISSUE TITLE
BUG ISSUES 

### ISSUE THREAD

**Issue by taint19711** [Dark-Arcana/antimatter-chemistry#140]
I did it by accident. I borke the controller for the alchemisty fission

**Comment by Next-victim** [comment]
Crashlog per the channel of discord:


java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=status, clazz=class al132.alchemistry.blocks.PropertyPowerStatus, values=[OFF, STANDBY, ON]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
    at al132.alchemistry.tiles.TileFusionController.func_73660_a(TileFusionController.kt:68)
    at cf.terminator.tiquality.tracking.tickexecutors.ForgeTickExecutor.onTileEntityTick(ForgeTickExecutor.java:30)
    at net.minecraft.tileentity.TileEntity.tiquality_doUpdateTick(TileEntity.java:627)
    at cf.terminator.tiquality.tracking.TrackerBase.updateOld(TrackerBase.java:181)
    at cf.terminator.tiquality.tracking.TrackerBase.doRandomBlockTick(TrackerBase.java:301)
    at cf.terminator.tiquality.tracking.TickHub.onRandomBlockTick(TickHub.java:43)
    at net.minecraft.world.WorldServer.redirect$onRandomBlockTick$zzi000(WorldServer.java:1941)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
